# Generated by Django 4.2.15 on 2025-05-22 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="account",
            fields=[
                ("name", models.CharField(max_length=32)),
                ("gender", models.CharField(max_length=25)),
                (
                    "phone",
                    models.DecimalField(decimal_places=0, max_digits=10, unique=True),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "aadhar",
                    models.DecimalField(decimal_places=0, max_digits=12, unique=True),
                ),
                (
                    "acc_num",
                    models.BigAutoField(
                        default=124019000000, primary_key=True, serialize=False
                    ),
                ),
                ("pin", models.CharField(default="000000", max_length=6)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("address", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
