# Generated by Django 4.2.20 on 2025-05-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="acc_num",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
